### ISSUE TITLE
21.02 release

### ISSUE THREAD

**Issue by benpro** [dangowrt/linksys-e8450-openwrt-installer#12]
Hello,

Current builds are using snapshot. Is the E8450 router a candidate to be available in next 21.02 release?

**Comment by dangowrt** [comment]
Unfortunately the answer is no. Support for the device was added after 21.02 had branched off, and is based on Kernel 5.10. There might be another release coming up later this year (branching October/November), and that will have support for it. Until then, you will have to use snapshots.
