### ISSUE TITLE
Fresh install of 0.5.2 - auc fails with Bad Message (74)

### ISSUE THREAD

**Issue by jpamills** [dangowrt/linksys-e8450-openwrt-installer#21]
Hello, I have successfully installed the 0.5.2 release, and am very happy with the performance of it!

I am looking to eventually upgrade to the snapshot releases, and tried running auc. Unfortunately, I can't get it to work, as the confirmation dialogue fails with "Bad Message (74)":

`root@Linksys00135:~# auc
auc (0.1.8-1)
Running:   SNAPSHOT r17114-349e2b7e65 on mediatek/mt7622 (linksys,e8450-ubi)
Available: SNAPSHOT r17417-38cb500516
Requesting package lists...
 kmod-usb-storage: 5.10.46-1 -> 5.10.60-1
 iwinfo: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 kmod-crypto-gf128: 5.10.46-1 -> 5.10.60-1
 kmod-usb-core: 5.10.46-1 -> 5.10.60-1
 kmod-usb-storage-uas: 5.10.46-1 -> 5.10.60-1
 iw: 5.9-8fab0c9e-2 -> 5.9-8fab0c9e-3
 kmod-crypto-manager: 5.10.46-1 -> 5.10.60-1
 rpcd: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 busybox: 1.33.1-11 -> 1.33.1-12
 kmod-crypto-ctr: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-hash: 5.10.46-1 -> 5.10.60-1
 kmod-nf-reject6: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-aead: 5.10.46-1 -> 5.10.60-1
 libiwinfo-lua: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 luci-mod-system: git-21.105.64372-8c6a29a -> git-21.230.38677-82035ee
 kmod-nf-flow: 5.10.46-1 -> 5.10.60-1
 kmod-lib-crc-ccitt: 5.10.46-1 -> 5.10.60-1
 getrandom: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 blockdev: 2.36.1-2 -> 2.37-1
 luci-theme-bootstrap: git-21.164.71389-e6a2cdb -> git-21.217.49862-be028dc
 kmod-pppoe: 5.10.46-1 -> 5.10.60-1
 kmod-pppox: 5.10.46-1 -> 5.10.60-1
 kmod-ipt-conntrack: 5.10.46-1 -> 5.10.60-1
 kmod-nf-reject: 5.10.46-1 -> 5.10.60-1
 procd-ujail: 2021-05-05-021ece84-2 -> 2021-08-15-104b49d6-2
 kmod-lib-crc16: 5.10.46-1 -> 5.10.60-1
 base-files: 1445-r17114-349e2b7e65 -> 1451-r17417-38cb500516
 kmod-nf-nat: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-crc32c: 5.10.46-1 -> 5.10.60-1
 kmod-mt7615e: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 netifd: 2021-06-04-50381d0a-1 -> 2021-07-26-440eb064-1
 uboot-envtools: 2021.01-35 -> 2021.01-38
 kmod-usb-xhci-hcd: 5.10.46-1 -> 5.10.60-1
 dnsmasq: 2.85-3 -> 2.85-7
 procd: 2021-05-05-021ece84-2 -> 2021-08-15-104b49d6-2
 kmod-crypto-hmac: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-sha256: 5.10.46-1 -> 5.10.60-1
 kmod-mt7615-common: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 luci-mod-status: git-21.188.54937-a6d957d -> git-21.223.26748-6142579
 kmod-mt76-connac: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 block-mount: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 kmod-crypto-seqiv: 5.10.46-1 -> 5.10.60-1
 kmod-fs-vfat: 5.10.46-1 -> 5.10.60-1
 kmod-usb3: 5.10.46-1 -> 5.10.60-1
 firewall: 2021-03-29-a4355a6f-1 -> 2021-08-14-40e5f6a2-1
 luci-app-firewall: git-21.154.29028-dc0cfc6 -> git-21.223.26742-406e6c8
 kmod-thermal: 5.10.46-1 -> 5.10.60-1
 kmod-nf-ipt: 5.10.46-1 -> 5.10.60-1
 wpad-openssl: 2021-05-22-b102f19b-20 -> 2021-05-22-b102f19b-31
 kmod-ip6tables: 5.10.46-1 -> 5.10.60-1
 odhcp6c: 2021-01-09-53f07e90-18 -> 2021-07-14-94adc8bb-18
 fstools: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 kmod-crypto-ghash: 5.10.46-1 -> 5.10.60-1
 kmod-fs-ext4: 5.10.46-1 -> 5.10.60-1
 kmod-hwmon-core: 5.10.46-1 -> 5.10.60-1
 kmod-nls-utf8: 5.10.46-1 -> 5.10.60-1
 luci-theme-openwrt-2020: git-21.168.43899-e8a6f0b -> git-21.223.72656-e0d385e
 kmod-nls-cp437: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-file: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 odhcpd-ipv6only: 2021-06-19-564d25e5-2 -> 2021-08-11-01b4e604-1
 kmod-mt7915e: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 kmod-crypto-ccm: 5.10.46-1 -> 5.10.60-1
 blockd: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 luci-base: git-21.187.21474-0e4b4c5 -> git-21.226.86205-376af36
 kmod-leds-gpio: 5.10.46-1 -> 5.10.60-1
 kmod-gpio-button-hotplug: 5.10.46-3 -> 5.10.60-3
 logd: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 kmod-mac80211: 5.10.46+5.10.42-1-1 -> 5.10.60+5.10.42-1-1
 luci-app-attendedsysupgrade: git-21.186.73763-cef330a -> git-21.234.36440-2a29911
 kmod-ipt-core: 5.10.46-1 -> 5.10.60-1
 attendedsysupgrade-common: 5 -> 6
 kmod-ppp: 5.10.46-1 -> 5.10.60-1
 kmod-fs-f2fs: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-null: 5.10.46-1 -> 5.10.60-1
 libiwinfo: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 kmod-mt7615-firmware: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 auc: 0.1.8-1 -> 0.2.2-2
 kmod-nf-conntrack: 5.10.46-1 -> 5.10.60-1
 kmod-nf-ipt6: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-gcm: 5.10.46-1 -> 5.10.60-1
 kmod-fs-autofs4: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-rpcsys: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 kmod-nls-iso8859-1: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-cmac: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-rng: 5.10.46-1 -> 5.10.60-1
 kmod-nf-conntrack6: 5.10.46-1 -> 5.10.60-1
 libgcc: 8.4.0-3 -> 10.3.0-3
 kmod-mt76-core: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 ubox: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 kmod-crypto-crc32: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-iwinfo: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 luci-mod-network: git-21.190.70785-e5626ec -> git-21.223.26751-2393289
 kmod-nls-base: 5.10.46-1 -> 5.10.60-1
 hostapd-common: 2021-05-22-b102f19b-20 -> 2021-05-22-b102f19b-31
 kmod-ipt-offload: 5.10.46-1 -> 5.10.60-1
 kmod-scsi-core: 5.10.46-1 -> 5.10.60-1
 kmod-slhc: 5.10.46-1 -> 5.10.60-1
 kmod-cfg80211: 5.10.46+5.10.42-1-1 -> 5.10.60+5.10.42-1-1
 kmod-ipt-nat: 5.10.46-1 -> 5.10.60-1
Are you sure you want to continue the upgrade process? [N/y] y
Bad message (74)
root@Linksys00135:~# `

I have also tried upgrading auc and related packages via opkg first, but that does not work either: 

`root@Linksys01338:~# auc -f
auc (0.2.2-2)
Server:    https://chef.libremesh.org
Running:   SNAPSHOT r17114-349e2b7e65 on mediatek/mt7622 (linksys,e8450-ubi)
Available: SNAPSHOT r17417-38cb500516
Requesting package lists...
 kmod-usb-storage: 5.10.46-1 -> 5.10.60-1
 iwinfo: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 kmod-crypto-gf128: 5.10.46-1 -> 5.10.60-1
 kmod-usb-core: 5.10.46-1 -> 5.10.60-1
 kmod-usb-storage-uas: 5.10.46-1 -> 5.10.60-1
 iw: 5.9-8fab0c9e-2 -> 5.9-8fab0c9e-3
 kmod-crypto-manager: 5.10.46-1 -> 5.10.60-1
 rpcd: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 busybox: 1.33.1-11 -> 1.33.1-12
 kmod-crypto-ctr: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-hash: 5.10.46-1 -> 5.10.60-1
 kmod-nf-reject6: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-aead: 5.10.46-1 -> 5.10.60-1
 libiwinfo-lua: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 luci-mod-system: git-21.105.64372-8c6a29a -> git-21.230.38677-82035ee
 kmod-nf-flow: 5.10.46-1 -> 5.10.60-1
 kmod-lib-crc-ccitt: 5.10.46-1 -> 5.10.60-1
 getrandom: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 blockdev: 2.36.1-2 -> 2.37-1
 luci-theme-bootstrap: git-21.164.71389-e6a2cdb -> git-21.217.49862-be028dc
 kmod-pppoe: 5.10.46-1 -> 5.10.60-1
 kmod-pppox: 5.10.46-1 -> 5.10.60-1
 kmod-ipt-conntrack: 5.10.46-1 -> 5.10.60-1
 kmod-nf-reject: 5.10.46-1 -> 5.10.60-1
 procd-ujail: 2021-05-05-021ece84-2 -> 2021-08-15-104b49d6-2
 kmod-lib-crc16: 5.10.46-1 -> 5.10.60-1
 base-files: 1445-r17114-349e2b7e65 -> 1451-r17417-38cb500516
 kmod-nf-nat: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-crc32c: 5.10.46-1 -> 5.10.60-1
 kmod-mt7615e: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 netifd: 2021-06-04-50381d0a-1 -> 2021-07-26-440eb064-1
 uboot-envtools: 2021.01-35 -> 2021.01-38
 kmod-usb-xhci-hcd: 5.10.46-1 -> 5.10.60-1
 dnsmasq: 2.85-3 -> 2.85-7
 procd: 2021-05-05-021ece84-2 -> 2021-08-15-104b49d6-2
 kmod-crypto-hmac: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-sha256: 5.10.46-1 -> 5.10.60-1
 kmod-mt7615-common: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 luci-mod-status: git-21.188.54937-a6d957d -> git-21.223.26748-6142579
 kmod-mt76-connac: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 block-mount: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 kmod-crypto-seqiv: 5.10.46-1 -> 5.10.60-1
 kmod-fs-vfat: 5.10.46-1 -> 5.10.60-1
 kmod-usb3: 5.10.46-1 -> 5.10.60-1
 firewall: 2021-03-29-a4355a6f-1 -> 2021-08-14-40e5f6a2-1
 luci-app-firewall: git-21.154.29028-dc0cfc6 -> git-21.223.26742-406e6c8
 kmod-thermal: 5.10.46-1 -> 5.10.60-1
 kmod-nf-ipt: 5.10.46-1 -> 5.10.60-1
 kmod-ip6tables: 5.10.46-1 -> 5.10.60-1
 odhcp6c: 2021-01-09-53f07e90-18 -> 2021-07-14-94adc8bb-18
 fstools: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 kmod-crypto-ghash: 5.10.46-1 -> 5.10.60-1
 kmod-fs-ext4: 5.10.46-1 -> 5.10.60-1
 kmod-hwmon-core: 5.10.46-1 -> 5.10.60-1
 kmod-nls-utf8: 5.10.46-1 -> 5.10.60-1
 luci-theme-openwrt-2020: git-21.168.43899-e8a6f0b -> git-21.223.72656-e0d385e
 kmod-nls-cp437: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-file: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 odhcpd-ipv6only: 2021-06-19-564d25e5-2 -> 2021-08-11-01b4e604-1
 kmod-mt7915e: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 kmod-crypto-ccm: 5.10.46-1 -> 5.10.60-1
 blockd: 2021-05-16-3d40a1b5-2 -> 2021-08-14-2e3aca29-1
 luci-base: git-21.187.21474-0e4b4c5 -> git-21.226.86205-376af36
 kmod-leds-gpio: 5.10.46-1 -> 5.10.60-1
 kmod-gpio-button-hotplug: 5.10.46-3 -> 5.10.60-3
 logd: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 kmod-mac80211: 5.10.46+5.10.42-1-1 -> 5.10.60+5.10.42-1-1
 libblobmsg-json: 2021-08-19-d716ac4b-2 -> 2021-05-16-b14c4688-2
 kmod-ipt-core: 5.10.46-1 -> 5.10.60-1
 kmod-ppp: 5.10.46-1 -> 5.10.60-1
 kmod-fs-f2fs: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-null: 5.10.46-1 -> 5.10.60-1
 libiwinfo: 2021-06-28-c9b1672f-2 -> 2021-07-11-a0a0e02d-1
 kmod-mt7615-firmware: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 kmod-nf-conntrack: 5.10.46-1 -> 5.10.60-1
 kmod-nf-ipt6: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-gcm: 5.10.46-1 -> 5.10.60-1
 kmod-fs-autofs4: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-rpcsys: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 kmod-nls-iso8859-1: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-cmac: 5.10.46-1 -> 5.10.60-1
 kmod-crypto-rng: 5.10.46-1 -> 5.10.60-1
 kmod-nf-conntrack6: 5.10.46-1 -> 5.10.60-1
 libgcc: 8.4.0-3 -> 10.3.0-3
 libubox: 2021-08-19-d716ac4b-2 -> 2021-05-16-b14c4688-2
 kmod-mt76-core: 5.10.46+2021-06-06-22b69033-4 -> 5.10.60+2021-07-15-bbebea7d-4
 ubox: 2020-10-25-9ef88681-2 -> 2021-08-03-205defb5-2
 kmod-crypto-crc32: 5.10.46-1 -> 5.10.60-1
 rpcd-mod-iwinfo: 2021-05-05-7a560a1a-1 -> 2021-07-13-1fa35765-1
 luci-mod-network: git-21.190.70785-e5626ec -> git-21.223.26751-2393289
 kmod-nls-base: 5.10.46-1 -> 5.10.60-1
 hostapd-common: 2021-05-22-b102f19b-20 -> 2021-05-22-b102f19b-31
 kmod-ipt-offload: 5.10.46-1 -> 5.10.60-1
 kmod-scsi-core: 5.10.46-1 -> 5.10.60-1
 kmod-slhc: 5.10.46-1 -> 5.10.60-1
 kmod-cfg80211: 5.10.46+5.10.42-1-1 -> 5.10.60+5.10.42-1-1
 kmod-ipt-nat: 5.10.46-1 -> 5.10.60-1
Are you sure you want to continue the upgrade process? [N/y] y
Bad message (74)
root@Linksys01338:~# `

What am I missing?

**Comment by dangowrt** [comment]
There has been an API hick-up with the update server. This has been fixed by now, however, it doesn't help much as by now you have to re-run the installer in order to be compatible with the most recent OpenWrt snapshots after openwrt/openwrt@050621a .
So best is (unfortunately) to backup you configuration and then re-flash the v0.5.3 [`openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb`](https://github.com/dangowrt/linksys-e8450-openwrt-installer/releases/download/v0.5.3/openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb)

**Comment by jpamills** [comment]
Thanks for the update! I will follow up with another issue in the forum thread.
