### ISSUE TITLE
Flash Openwrt successed. What should i do, if i want to return on Original factory firmware without backup

### ISSUE THREAD

**Issue by dengrongfei** [dangowrt/linksys-e8450-openwrt-installer#36]
As the title says, I did not back up the original firmware.
Can it be used normally if I restore the original firmware backed up from other machines? 
By contrast, I prefer like the Netgear R7000 flash method. Can be flexibly switched Merlin and original firmware on the web page

**Comment by mrkiko** [comment]
The installer should take a backup for you, but depending on how recently you did run it and how many times you did so, your backup files may be related to stock firmware or not.
You may also have a look at issue #14 for some details on the matter.
