### ISSUE TITLE
router blocked to initframs after instal 0.6.1

### ISSUE THREAD

**Issue by neilsan1366** [dangowrt/linksys-e8450-openwrt-installer#41]
hello my router is block to initsframs after install 0.6.1 
after i has try snapshot but don't work 
how to resolv ?

thanks

**Comment by mrkiko** [comment]
Hello!
After re-running the installer, you need to sysupgrade again, using a squashfs sysupgrade image. Be sure to use an image for the UBI layout.
If you did so already, may I ask you to check if/sys /fs /pstore folder is empty? If not, please remove all the files within it.
