### ISSUE TITLE
Looks like build script is failing because public keys have expired

### ISSUE THREAD

**Issue by munro** [dangowrt/linksys-e8450-openwrt-installer#43]
https://github.com/dangowrt/linksys-e8450-openwrt-installer/blob/a96977bc22ad8f0dbc69f769b60ece8b88719de3/build_installer.sh#L29-L30

https://github.com/dangowrt/linksys-e8450-openwrt-installer/blob/a96977bc22ad8f0dbc69f769b60ece8b88719de3/build_installer.sh#L34

Is giving me

```
gpg: error reading key: No public key
```

It looks like the keys have expired

https://keyserver.ubuntu.com/pks/lookup?search=0xCD84BCED626471F1&fingerprint=on&op=index

After commenting those lines out though, `bash build_installer.sh` worked perfectly :smile:

**Comment by dangowrt** [comment]
Most likely a problem with the keyserver, see

https://openwrt.org/docs/guide-user/security/signatures?s[]=pgp#pgp_key_for_unattended_snapshot_builds
