### ISSUE TITLE
sysupgrade

### ISSUE THREAD

**Issue by levshutov** [dangowrt/linksys-e8450-openwrt-installer#51]
Hi.

I installed v0.6.1 over stock firmware following your instructions. Works fine.

I used to perform command line "sysupgrade openwrt-***-sysupgrade.bin" for other routers for native builds when I want to upgrade. It handles configs transfer.

You will have new release sooner or later.
Is it safe to perform "sysupgrade openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb" from "production" environment (not recovery)?

Thanks.

**Comment by dangowrt** [comment]
Yes, that's safe to do, you can just sysupgrade with updated builds from here, builds you made yourself or snapshots from downloads.openwrt.org. Really nothing can go wrong as a broken, unbootable or crashing image will result in the device rebooting into the recovery image which came with the installer.

**Comment by levshutov** [comment]
Thanks.
