### ISSUE TITLE
add AES supports 

### ISSUE THREAD

**Issue by ericvwv** [dangowrt/linksys-e8450-openwrt-installer#61]
As we know the A53 core supports AES, Normally, the AES test should be about 550K, but the score was only around 55K.   It is sure that AES is work abnormally. I'm sure I've found the solution, but I don't know where to add these two options in build_installer.sh 

CONFIG_PACKAGE_libmbedtls=y
CONFIG_LIBMBEDTLS_HAVE_ARMV8CE_AES=y

AES test score==================================================
root@E8450:~# openssl speed -evp aes-128-gcm
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      37646.77k    49596.20k    54220.89k    56560.84k    55971.36k    55974.10k

**Comment by mrkiko** [comment]
This issue doesn't seem related to this project.
Instead, it seems a more general OpenWRt configuration issue.

**Comment by ericvwv** [comment]
U are right.  Please close this issue.
thanks for your work.

**Comment by mrkiko** [comment]
Oh - it's all Daniel's :) :)
