### ISSUE TITLE
Priority problem of kmod-* packages.

### ISSUE THREAD

**Issue by virus-warnning** [dangowrt/linksys-e8450-openwrt-installer#66]
I have installed v0.6.1 on my E8450 recently.
Kernel version is 5.10.80-1.
A dependency warning appeared while I install strongswan-full.

![strongswan-01](https://user-images.githubusercontent.com/5044734/152721465-6f5019af-f1d5-4ae9-8d5a-adeb41cc143c.png)

It's my OPKG configuration.

![strongswan-02](https://user-images.githubusercontent.com/5044734/152723201-9a86915e-14dc-4cc5-b52c-fd3b855e74d0.png)

**kmod-crypto-authenc_5.10.96-1_aarch64_cortex-a53.ipk** can be found at
https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/packages/

**kmod-crypto-authenc_5.10.80-1_aarch64_cortex-a53.ipk** can be found at
https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/kmods/5.10.80-1-a3398c593d3440164c247a13bc67d164/

The priority of 5.10.96 is higher than 5.10.80.

So I move openwrt_kmods to first line and update list again, then depencency tree is okay.

```
src/gz openwrt_kmods https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/kmods/5.10.80-1-a3398c593d3440164c247a13bc67d164
src/gz openwrt_core https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/packages
src/gz openwrt_base https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony
```

![strongswan-03](https://user-images.githubusercontent.com/5044734/152724800-f806561d-4fa9-4c9d-9a74-7ff65e16fa95.png)

After install strongswan-full, exit code 256 returned.
Kernel 5.10.96 is still required.

![strongswan-04](https://user-images.githubusercontent.com/5044734/152724931-cc3f9aec-022d-488f-8d71-c3d1881d5b1c.png)

How may I solve this problem?

**Comment by mrkiko** [comment]
Hello!!

This project aims to give you an open bootchain with nice recovery system, setting up the system with UBI, thus managing the flash chip correctly.
From here, you should sysupgrade to a snapshot openwrt build for ubi layout, or build one yourself. At that point your dependency issue should be solved.
This issue doesn't seem related to this project.

**Comment by virus-warnning** [comment]
Thanks
