### ISSUE TITLE
[Suggestion] Add checksums in release section

### ISSUE THREAD

**Issue by t3dium** [dangowrt/linksys-e8450-openwrt-installer#76]
Great script btw, worked flawlessly on my device. Could you also add sha 256 checksums for the image though, as a corrupt download could brick the router.

installer image: 3ca00588e01c6fb41084ded41929384a8a8717e830dfd2a1ba77c645f808cdb3 

sysupgrade image: fc9ae29b9c1bc4f8d95de062e44818d918bd29c93c7ab9ff80975616f4fff6ab

**Comment by dangowrt** [comment]
Unfortunately this is not possible at this point as the script relies on downloading *nightly snapshot builds* from downloads.openwrt.org which are subject to change. I will do this once 22.xx is released as we can then rely on reproducible binaries. As a temporary work-around I could add some size-checks to at least make sure the result roughly matches the expected outcome...
