### ISSUE TITLE
upgrade uboot only

### ISSUE THREAD

**Issue by ex-git** [dangowrt/linksys-e8450-openwrt-installer#77]
Coming from a early version uboot. Is it possible to just upgrade uboot only and how?

**Comment by dangowrt** [comment]
I don't see a real reason which would justify the risk (updating U-Boot always is a risk and if things go wrong, JTAG will be the only way forward...).
Once again: There is **no** advantage (as in **zero**) to do this at this point, nothing significant has been fixed or updated in U-Boot when it comes to load OpenWrt from UBI.

However, you can still do it if you really want, but don't blame me if things go wrong.
You may do when using the serial console connected and use the menu displayed by the bootloader, there is an option `Load BL31+U-Boot FIP via TFTP then write to flash.` which does exactly what it says.
You can also do the same from inside OpenWrt (or recovery firmware)
```
cd /tmp
wget https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/openwrt-mediatek-mt7622-linksys_e8450-ubi-bl31-uboot.fip
# best is of course to validate the downloaded file, eg. using sha256sum
insmod mtd_rw i_want_a_brick=1
mtd write openwrt-mediatek-mt7622-linksys_e8450-ubi-bl31-uboot.fip /dev/mtd1
# make sure environment is re-created by updated U-Boot
ubirmvol /dev/ubi0 --name ubootenv
ubirmvol /dev/ubi0 --name ubootenv2
# done
reboot
```

After reboot, you should see the new version written to the U-Boot environment, ie. verify using `fw_printenv ver`.

**Comment by ex-git** [comment]
thanks.
