### ISSUE TITLE
Kernel too old for wireguard

### ISSUE THREAD

**Issue by DavidM42** [dangowrt/linksys-e8450-openwrt-installer#78]
When I try to install the WireGuard VPN package, I receive feedback that the installed kernel is too old
```
Require version = 5.10.102-1-c52cbcf17c7afa063d140662123758e1,
installed 5.10.92-1-df7cd26da92fdd5f2ede827f1b1112a7
```

I installed the `Release v.0.6.2` from this project.
Is it preferable for me to update the snapshot via attended sysupgrade or try to compile my own version myself locally?

**Comment by dangowrt** [comment]
Using `auc` or the attended-sysupgrade LuCI app is by far the easiest way to do this. If you want to build from source (so you won't need to trust binaries from our servers) you can do that as well -- and even if things go very wrong, you will still be able to recover easily.
