### ISSUE TITLE
Maximum transmit power seems not to work

### ISSUE THREAD

**Issue by WiredLife** [dangowrt/linksys-e8450-openwrt-installer#80]
hello,
i set my region to panama (PA) and Maximum transmit power shows "Current power: 27 dBm"
but it seems it does not change the tx power
is there a way to get the max power output?
maybe change something in the firmware?

**Comment by mrkiko** [comment]
Hello!

This issue does not seem related to this project, which aims to create an installer to switch the device to an open-source updated bootchain and using UBI.

You may have better luck by posting on the OpenWRt forum.

**Comment by dangowrt** [comment]
@WiredLife I agree with @mrkiko that this is not an issue with the installer but could either be a hardware limitation or tx-power not being handled correctly by the [mt76](https://www.github.com/openwrt/mt76) driver.
